{
 "title": "Feldera OTel",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Execution Time by Operation",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT sum(elapsed) as elapsed, name FROM operation_execution_time\nGROUP BY name"
    }
   ]
  },
  {
   "title": "Histogram of Latencies",
   "type": "histogram",
   "gridPos": { "h": 13, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "queryText": "SELECT s.elapsedTimeMillis\nFROM spans s\nWHERE s.parentSpanId = '' AND\ns.eventTime between $__timeFrom() and $__timeTo()\nORDER BY s.eventTime DESC"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 13 },
   "targets": [
    {
     "queryText": "select count(*) as num_traces from spans s\nwhere s.parentSpanId = '' and s.eventTime between $__timeFrom() and $__timeTo()"
    }
   ]
  },
  {
   "title": "Slowest Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 13 },
   "targets": [
    {
     "queryText": "SELECT s.traceId, s.name, s.elapsedTimeMillis\nFROM spans s\nWHERE s.parentSpanId = '' AND\ns.eventTime between $__timeFrom() and $__timeTo()\nORDER BY elapsedTimeMillis DESC\nLIMIT 6\n"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "queryText": "select * from throughput where time between $__timeFrom() and $__timeTo() order by time desc"
    }
   ]
  },
  {
   "title": "P95 Latencies",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "queryText": "select * from p95_latency where time between $__timeFrom() and $__timeTo() order by time desc"
    }
   ]
  }
 ]
}